/// All sales unified: ERP, MegaMart marketplace (net = payout after ~14% fees; gross = before fees), and Lakeside stores. The source column identifies origin. sku='UNMAPPED' marks stale marketplace listings.
table c_fact_sales_unified
	lineageTag: 34a9b249-7c8a-411b-8074-3eccef054fb2

	column source
		dataType: string
		summarizeBy: none
		sourceColumn: source
		lineageTag: 6dd449e6-b8cb-4bea-9a12-1c03209c62e4

	column date_key
		dataType: int64
		summarizeBy: none
		sourceColumn: date_key
		lineageTag: 9f5795ee-e460-4594-a470-49f7be7f028b

	column sku
		dataType: string
		summarizeBy: none
		sourceColumn: sku
		lineageTag: 4e41b3aa-aea4-4d7a-a4ba-edfc59b38771

	column location_id
		dataType: string
		summarizeBy: none
		sourceColumn: location_id
		lineageTag: 2c0998b0-135e-4688-b92b-5dd7712c44b7

	column channel
		dataType: string
		summarizeBy: none
		sourceColumn: channel
		lineageTag: ec34d45d-0e1e-493c-a17e-e28a48ef7004

	column qty
		isHidden
		dataType: int64
		summarizeBy: sum
		sourceColumn: qty
		lineageTag: 29ba9471-5c56-495b-89a6-238071dddbec

	column gross_amount
		isHidden
		dataType: double
		summarizeBy: sum
		sourceColumn: gross_amount
		lineageTag: 6d04d92c-f9c9-49a3-acc3-bd5df275ff2b

	column net_amount
		isHidden
		dataType: double
		summarizeBy: sum
		sourceColumn: net_amount
		lineageTag: 8d2cb3b1-ba33-40ec-af8e-b7ddb588388e

	/// Gross revenue, all sources.
	measure 'Revenue Gross' = SUM ( c_fact_sales_unified[gross_amount] )
		formatString: #,##0
		lineageTag: 7845d2ab-e7ff-40ea-9d29-bac01905d5f3

	/// Net revenue (marketplace net of fees).
	measure 'Revenue Net' = SUM ( c_fact_sales_unified[net_amount] )
		formatString: #,##0
		lineageTag: cb489166-ad28-4c59-9c62-64d4a016fdb7

	measure 'Units Sold' = SUM ( c_fact_sales_unified[qty] )
		formatString: #,##0
		lineageTag: 55e9d8ab-b640-446e-ad55-2099988fc192

	measure 'ERP Revenue' = CALCULATE ( [Revenue Net], c_fact_sales_unified[source] = "ERP" )
		formatString: #,##0
		lineageTag: 386f70f9-d1a1-4902-8a1e-ab4c868247da

	measure 'Marketplace Net Revenue' = CALCULATE ( [Revenue Net], c_fact_sales_unified[source] = "MegaMart" )
		formatString: #,##0
		lineageTag: efeceba0-c1a1-48fd-8482-b15834450c1b

	measure 'Marketplace Gross Revenue' = CALCULATE ( [Revenue Gross], c_fact_sales_unified[source] = "MegaMart" )
		formatString: #,##0
		lineageTag: 07bc71a7-8b5e-468e-b7b0-f1b3ba835a1f

	measure 'Lakeside Revenue' = CALCULATE ( [Revenue Net], c_fact_sales_unified[source] = "Lakeside" )
		formatString: #,##0
		lineageTag: 1e13978b-61eb-4778-86b7-924b9c0e425f

	/// Share of daily ERP snapshot rows in stockout.
	measure 'Stockout Rate %' = DIVIDE ( CALCULATE ( SUM ( c_fact_inventory[is_stockout] ), c_fact_inventory[grain] = "daily" ), CALCULATE ( COUNTROWS ( c_fact_inventory ), c_fact_inventory[grain] = "daily" ) )
		formatString: 0.0%
		lineageTag: d72ca640-a337-47fe-879a-a524f4e4cdd1

	measure 'Avg On-Hand Units' = AVERAGEX ( VALUES ( c_dim_date[date_key] ), CALCULATE ( SUM ( c_fact_inventory[on_hand_qty] ) ) )
		formatString: #,##0
		lineageTag: 28169f41-da1f-40ab-a9fb-cdf5a9298bcb

	measure 'Sell-Through Ratio' = DIVIDE ( [Units Sold], [Avg On-Hand Units] )
		formatString: 0.00
		lineageTag: 37212e7e-e11e-4f38-a46a-22a965fdfcea

	measure Tickets = COUNTROWS ( c_fact_helpdesk )
		formatString: #,##0
		lineageTag: 21ba9ca2-3a46-498f-8b04-b1809f005a96

	/// Open tickets in the Product complaint category.
	measure 'Open Complaints' = CALCULATE ( [Tickets], c_fact_helpdesk[is_complaint] = TRUE, c_fact_helpdesk[is_open] = TRUE )
		formatString: #,##0
		lineageTag: 78e2ffb5-a66b-43db-bac4-514930a10f5b

	measure 'Tickets per 1K Units' = DIVIDE ( [Tickets], [Units Sold] ) * 1000
		formatString: 0.0
		lineageTag: 1da397c9-3de3-4be4-9b6b-e0c295862a1b

	measure 'Parts per 100 Units' = DIVIDE ( SUM ( c_fact_service_parts[qty_used] ), [Units Sold] ) * 100
		formatString: 0.0
		lineageTag: d564d8a6-0030-46f1-898a-1543ef39ae96

	partition c_fact_sales_unified = entity
		mode: directLake
		source
			entityName: c_fact_sales_unified
			expressionSource: DatabaseQuery

